pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials ('ACCESS_KEY_ID')
        AWS_SECRETE_ACCESS_KEY = credentials ('SECRETE_ACCESS_KEY')
        AWS_DEFAULT_REGION = "ap-south-1"
    }

    stages {
        stage('Checkout-SCM') {
            steps {
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/kvmuralikrishna9/Testing.git']])
                }
            }
        }

        stage('Initializing Terraform'){
            steps {
                script{
                    dir('c_eks_from_jenkins'){
                        sh 'terraform init'
                    }   
                }
            }
        }

        stage('Formatting Terraform code'){
            steps {
                script{
                    dir('c_eks_from_jenkins') {
                        sh 'terraform fmt'
                    }   
                }
            }
        }

        stage('Validating Terraform code'){
            steps {
                script{
                    dir('c_eks_from_jenkins') {
                        sh 'terraform validate'
                    }   
                }
            }
        }

        stage('Previewing the Infra using terraform') {
            steps {
                script{
                    dir('c_eks_from_jenkins') {
                        sh 'terraform plan -out=c_eks_from_jenkins.tfplan'
                    }  
                  //input(message: "Are you sure to proceed?", ok: "proceed")
                }
            }
        }

        stage('Creating/Destroying EKS cluster'){
            steps {
                script{
                    dir('c_eks_from_jenkins') {
                        sh 'terraform $action --auto-approve'    //parameterized
                    }  
                }
            }
        }

        stage('Deploying the Nginx Application'){
            steps {
                script{
                    dir('c_eks_from_jenkins/ConfigurationFiles') {
                        sh 'aws eks update-kubeconfig --name eks-tf_cluster'
                        sh 'kubectl apply -f deployment.yaml'
                        sh 'kubectl apply -f service.yaml'
                    }  
                }
            }
        }
    }
}

