# Values are just for the refernce, we can go as we like"

vpc_cidr_block = "146.0.0.0/16"          
vpc_name = "eks-tf_vpc"
env_name = "development-team"
cidr_block_pub_subnet = "146.0.1.0/24"
availability_zone_pub_sub = "ap-south-1a"
public_subnet_name = "public_subnet"
cidr_block_pvt_subnet = "146.0.2.0/24"
availability_zone_pvt_sub = "ap-south-1a"
private_subnet_name = "public_subnet"
vpc_igw = "eks-tf_vpc_igw"
route_table_name = "eks-tf_vpc_route_tale"