pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials ('ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials ('SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "ap-south-1"
    }

    stages {
        stage('Checkout-SCM'){
            steps {
                script{
                   checkout scmGit(branches: [[name: '*/feature-branch']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/kvmuralikrishna9/DevOps_Practise.git']])
                }
            }
        }

        stage('Initializing Terraform'){
            steps {
                script{
                    dir('terraform/7_EKS_deploy-from-Jenkins/c_eks_from_jenkins') {
                        sh 'terraform init'
                    }  
                }
            }
        }

	stage('Formatting TF-Code'){
            steps {
                script{
                    dir('terraform/7_EKS_deploy-from-Jenkins/c_eks_from_jenkins') {
                        sh 'terraform fmt'
                    }
                }
            }
        }

	stage('Validating TF-Code'){
            steps {
                script{
                    dir('terraform/7_EKS_deploy-from-Jenkins/c_eks_from_jenkins') {
                        sh 'terraform validate'
                    }
                }
            }
        }

	stage('Previewing the infrastructure'){
            steps {
                script{
                    dir('terraform/7_EKS_deploy-from-Jenkins/c_eks_from_jenkins') {
                        sh 'terraform plan -out=c_eks_from_jenkins.tfplan'
                    }
                }
            }
        }


        stage('Creating EKS cluster'){
            steps {
                script{
                    dir('terraform/7_EKS_deploy-from-Jenkins/c_eks_from_jenkins') {
                        sh 'terraform apply --auto-approve'    //parameterized
                    }  
                }
            }
        }

        stage('Updating Kubeconfig on EKS Cluster'){
            steps {
                script{
                    dir('terraform/7_EKS_deploy-from-Jenkins/c_eks_from_jenkins') {
                        sh 'aws eks update-kubeconfig --name eks-tf_cluster --region ap-south-1'
                    }  
                }
            }
        }

        /*stage('Deploying the Nginx Application'){
            steps {
                script{
                    dir('c_eks_from_jenkins/ConfigurationFiles') {
                        sh 'aws eks update-kubeconfig --name eks-tf_cluster --region ap-south-1'
                        sh 'kubectl apply -f deployment.yaml'
                        sh 'kubectl apply -f service.yaml'
                    }  
                }
            } 
        }*/
    }
}
